//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kovorkingg
{
    using System;
    using System.Collections.Generic;
    
    public partial class booking_items
    {
        public int id { get; set; }
        public int booking_id { get; set; }
        public int item_id { get; set; }
        public int quantity { get; set; }
        public decimal price { get; set; }
    
        public virtual bookings bookings { get; set; }
        public virtual items items { get; set; }
    }
}
