//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kovorkingg
{
    using System;
    using System.Collections.Generic;
    
    public partial class bookings
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public bookings()
        {
            this.booking_items = new HashSet<booking_items>();
        }
    
        public int id { get; set; }
        public int user_id { get; set; }
        public int client_id { get; set; }
        public System.DateTime booking_date { get; set; }
        public System.TimeSpan start_time { get; set; }
        public System.TimeSpan end_time { get; set; }
        public decimal total_amount { get; set; }
        public string status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<booking_items> booking_items { get; set; }
        public virtual clients clients { get; set; }
        public virtual users users { get; set; }
    }
}
